### ISSUE TITLE
Другие операторы

### ISSUE THREAD

**Issue by zavertyaev** [psyX/pbal#1]
Насколько сложно добавить других операторов, например Теле2 (my.tele2.ru) и Мегафон других регионов (kavkazsg.megafon.ru)?

**Comment by psyX** [comment]
если дадите логины протестировать могу попробовать написать... psyx83@gmail.com

**Comment by zavertyaev** [comment]
Возможно использовать это https://github.com/agentsib/useful-scripts/blob/master/bash/mobile/tele2.sh ? Проверено, работает.

**Comment by psyX** [comment]
да, но в том скрипте нет обработки ошибки не корректного логина\пароля

**Comment by psyX** [comment]
мегафон должен работать, теле2 нет возможности попробовать
