### ISSUE TITLE
Мегафон проще проверять через ServiceGid

### ISSUE THREAD

**Issue by agentsib** [psyX/pbal#2]
https://github.com/agentsib/useful-scripts/blob/master/bash/mobile/megafon.sh
Вот пример проверки.

Активация все там же в личном кабинете. Нужно выставить разрешение для бота.

**Comment by psyX** [comment]
на сайте kavkazsg.megafon.ru я вижу капчу, раньше правда на moscow.megafon.ru было так же и вроде бы можно это отключить (возможно это как раз про бота)

**Comment by agentsib** [comment]
Не то. У мегафона есть единый сервис гид. Формат отдачи XML. В моем примере он как раз и юзается. Для того, чтобы была возможность его использовать - в личном кабинете есть настройка. К сожалению я не могу туда в данный момент зайти, так как нет мегафоновской симки.

**Comment by agentsib** [comment]
http://s11.postimage.org/ifn2dacz5/SG_Mega_Fon_Roboty.jpg - вот тут включается. Далее запрос по АПИ.

http://sg.megafon.ru

**Comment by psyX** [comment]
сделал через сервис-гид.
