### ISSUE TITLE
mts.ru - перестал работать

### ISSUE THREAD

**Issue by Krong** [psyX/pbal#5]
mts.ru - перестал работать

**Comment by Krong** [comment]
Запрос https://login.mts.ru/amserver/UI/Login?service=lk&goto=https://lk.ssl.mts.ru/ работает правильно, но rv=$(resp "$tmp_file") возвращает 404.
Если после 
page="https://login.mts.ru/amserver/UI/Login?service=lk&goto=https://lk.ssl.mts.ru/"
грубо закомментить
#while [ "$rv" != "200" ]; do
#err404 "$page"
#done
или исправить функцию resp, то скрипт выполнятся дальше.
далее меняем
page="https://login.mts.ru/profile/mobile/get"
на
page="https://lk.ssl.mts.ru/policy/pa.get?_=1355651948698" (тут конечно нужно генерить случайное число из даты)
и
balance=`sed -n -e 's/.*balance":"\(.*\)","tariff.*/\1/p' $tmp_file`
на
balance=`grep Balance $tmp_file |  awk -F\" '{print $4}'`
то получим баланс.

**Comment by psyX** [comment]
МТС поправил

**Comment by psyX** [comment]
????????, ?????? ????????.
